name: upbit_dart
description: upbit API
version: 0.1.0

repository: https://github.com/Beta5051/upbit_dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3
  uuid: ^3.0.4
  crypto: ^3.0.1
  jaguar_jwt: ^3.0.0
  web_socket_channel: ^2.1.0
