name: upbit
description: upbit API
version: 0.1.0

repository: https://github.com/Beta5051/upbit.dart

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  http: ^0.13.4
  web_socket_channel: ^2.1.0
  uuid: ^3.0.5
  crypto: ^3.0.1
  dart_jsonwebtoken: ^2.4.0